<a href="https://colab.research.google.com/github/AbhijithReddie/Accident-Analysis/blob/main/Accident_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ============================================================
# STEP 1: IMPORT PACKAGES
# RTA / ACCIDENT DATASET ANALYSIS
# ============================================================

# ------------------------------------------------------------
# DATA MANIPULATION
# ------------------------------------------------------------

import pandas as pd
import numpy as np


# ------------------------------------------------------------
# DATA VISUALIZATION
# ------------------------------------------------------------

import matplotlib.pyplot as plt
import seaborn as sns


# ------------------------------------------------------------
# STATISTICAL ANALYSIS
# ------------------------------------------------------------

from scipy import stats


# ------------------------------------------------------------
# DISPLAY SETTINGS
# ------------------------------------------------------------

# Display all columns when viewing DataFrames
pd.set_option('display.max_columns', None)

# Display up to 100 rows when required
pd.set_option('display.max_rows', 100)

# Display numerical values up to 3 decimal places
pd.set_option('display.float_format', lambda x: '%.3f' % x)


# ------------------------------------------------------------
# VISUALIZATION SETTINGS
# ------------------------------------------------------------

# Set professional visualization style
sns.set_theme(style="whitegrid")

# Default figure size
plt.rcParams['figure.figsize'] = (10, 6)

# Improve chart readability
plt.rcParams['axes.titlesize'] = 14
plt.rcParams['axes.labelsize'] = 11
plt.rcParams['xtick.labelsize'] = 10
plt.rcParams['ytick.labelsize'] = 10


# ------------------------------------------------------------
# CONFIRMATION
# ------------------------------------------------------------

print("All required packages have been imported successfully.")

All required packages have been imported successfully.

In [ ]:
# ============================================================
# STEP 2: READ DATA & INITIAL DATA UNDERSTANDING
# RTA / ACCIDENT DATASET ANALYSIS
# ============================================================


# ------------------------------------------------------------
# 2.1 IMPORT / UPLOAD DATASET
# ------------------------------------------------------------
# ------------------------------------------------------------
# 2.2 READ THE CSV FILE
# ------------------------------------------------------------

file_name = "RTA_Dataset.csv"

df = pd.read_csv("/content/RTA_Dataset.csv")


# ------------------------------------------------------------
# 2.3 CREATE A BACKUP OF THE ORIGINAL DATA
# ------------------------------------------------------------

# Keeping a copy allows us to compare the cleaned dataset
# with the original dataset later.

df_original = df.copy()


# ------------------------------------------------------------
# 2.4 DISPLAY BASIC INFORMATION
# ------------------------------------------------------------

print("=" * 70)
print("DATASET LOADED SUCCESSFULLY")
print("=" * 70)

print(f"\nDataset Name      : {file_name}")
print(f"Number of Rows    : {df.shape[0]:,}")
print(f"Number of Columns : {df.shape[1]:,}")


# ------------------------------------------------------------
# 2.5 DISPLAY FIRST 5 RECORDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("FIRST 5 RECORDS")
print("=" * 70)

display(df.head())


# ------------------------------------------------------------
# 2.6 DISPLAY LAST 5 RECORDS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("LAST 5 RECORDS")
print("=" * 70)

display(df.tail())


# ------------------------------------------------------------
# 2.7 DATASET DIMENSIONS
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATASET DIMENSIONS")
print("=" * 70)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]:,}")


# ------------------------------------------------------------
# 2.8 COLUMN NAMES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("COLUMN NAMES")
print("=" * 70)

for i, column in enumerate(df.columns, start=1):
    print(f"{i:2}. {column}")


# ------------------------------------------------------------
# 2.9 DATA TYPES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATA TYPES")
print("=" * 70)

display(
    pd.DataFrame({
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values
    })
)


# ------------------------------------------------------------
# 2.10 DATASET INFORMATION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATASET INFORMATION")
print("=" * 70)

df.info()


# ------------------------------------------------------------
# 2.11 NUMERICAL COLUMNS
# ------------------------------------------------------------

numerical_columns = df.select_dtypes(
    include=np.number
).columns.tolist()

print("\n" + "=" * 70)
print("NUMERICAL COLUMNS")
print("=" * 70)

print(f"Number of numerical columns: {len(numerical_columns)}")

for column in numerical_columns:
    print(f"- {column}")


# ------------------------------------------------------------
# 2.12 CATEGORICAL / OBJECT COLUMNS
# ------------------------------------------------------------

categorical_columns = df.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("\n" + "=" * 70)
print("CATEGORICAL / OBJECT COLUMNS")
print("=" * 70)

print(f"Number of categorical columns: {len(categorical_columns)}")

for column in categorical_columns:
    print(f"- {column}")


# ------------------------------------------------------------
# 2.13 STATISTICAL SUMMARY - NUMERICAL VARIABLES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STATISTICAL SUMMARY - NUMERICAL VARIABLES")
print("=" * 70)

if len(numerical_columns) > 0:
    display(
        df[numerical_columns].describe().T
    )
else:
    print("No numerical columns detected.")


# ------------------------------------------------------------
# 2.14 STATISTICAL SUMMARY - CATEGORICAL VARIABLES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STATISTICAL SUMMARY - CATEGORICAL VARIABLES")
print("=" * 70)

if len(categorical_columns) > 0:
    display(
        df[categorical_columns].describe().T
    )
else:
    print("No categorical columns detected.")


# ------------------------------------------------------------
# 2.15 UNIQUE VALUES IN EACH COLUMN
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("NUMBER OF UNIQUE VALUES PER COLUMN")
print("=" * 70)

unique_summary = pd.DataFrame({
    "Column": df.columns,
    "Unique_Values": df.nunique(dropna=False).values,
    "Missing_Values": df.isna().sum().values
})

display(
    unique_summary.sort_values(
        by="Unique_Values",
        ascending=False
    ).reset_index(drop=True)
)


# ------------------------------------------------------------
# 2.16 SAMPLE OF UNIQUE VALUES
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("SAMPLE UNIQUE VALUES FOR EACH COLUMN")
print("=" * 70)

for column in df.columns:

    unique_values = df[column].dropna().unique()

    print(f"\n{column}")
    print("-" * len(column))

    # Show maximum 15 unique values to avoid excessive output
    print(unique_values[:15])

    if len(unique_values) > 15:
        print(f"... and {len(unique_values) - 15} more unique values")


# ------------------------------------------------------------
# 2.17 MISSING VALUE OVERVIEW
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("MISSING VALUE OVERVIEW")
print("=" * 70)

missing_summary = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().mean().values * 100
    )
})

missing_summary = missing_summary.sort_values(
    by="Missing_Count",
    ascending=False
).reset_index(drop=True)

display(missing_summary)


# ------------------------------------------------------------
# 2.18 DUPLICATE RECORD COUNT
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DUPLICATE RECORD CHECK")
print("=" * 70)

duplicate_count = df.duplicated().sum()

print(f"Number of duplicate rows: {duplicate_count:,}")

if duplicate_count == 0:
    print("No exact duplicate records detected.")
else:
    print("Duplicate records detected and will be investigated in Data Cleaning.")


# ------------------------------------------------------------
# 2.19 TARGET VARIABLE INITIAL CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("ACCIDENT SEVERITY - INITIAL DISTRIBUTION")
print("=" * 70)

if "Accident_severity" in df.columns:

    severity_summary = pd.DataFrame({
        "Count": df["Accident_severity"].value_counts(dropna=False),
        "Percentage": (
            df["Accident_severity"]
            .value_counts(normalize=True, dropna=False) * 100
        )
    })

    display(severity_summary)

else:
    print("Accident_severity column not found.")


# ------------------------------------------------------------
# 2.20 CASUALTY SUMMARY
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("NUMBER OF CASUALTIES - INITIAL SUMMARY")
print("=" * 70)

if "Number_of_casualties" in df.columns:

    display(
        df["Number_of_casualties"].describe()
    )

    print(
        f"\nTotal casualties recorded: "
        f"{df['Number_of_casualties'].sum():,.0f}"
    )

else:
    print("Number_of_casualties column not found.")


# ------------------------------------------------------------
# 2.21 TIME COLUMN INITIAL INSPECTION
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("TIME COLUMN - INITIAL INSPECTION")
print("=" * 70)

if "Time" in df.columns:

    print(f"Data type of Time column: {df['Time'].dtype}")

    print("\nSample time values:")
    display(df["Time"].head(10))

    print("\nNumber of unique time values:")
    print(df["Time"].nunique())

else:
    print("Time column not found.")


# ------------------------------------------------------------
# 2.22 DATASET MEMORY USAGE
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("DATASET MEMORY USAGE")
print("=" * 70)

memory_usage = df.memory_usage(deep=True).sum() / (1024 ** 2)

print(f"Memory used by dataset: {memory_usage:.2f} MB")


# ------------------------------------------------------------
# 2.23 FINAL INITIAL CHECK
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("STEP 2 COMPLETED")
print("=" * 70)

print(f"Dataset shape : {df.shape}")
print(f"Rows          : {len(df):,}")
print(f"Columns       : {len(df.columns)}")
print(f"Duplicates    : {duplicate_count:,}")
print(f"Memory usage  : {memory_usage:.2f} MB")

print("\nThe dataset is now loaded and initially understood.")
print("Detailed cleaning and treatment will be performed in Step 3.")

======================================================================
DATASET LOADED SUCCESSFULLY
======================================================================

Dataset Name      : RTA_Dataset.csv
Number of Rows    : 12,316
Number of Columns : 32

======================================================================
FIRST 5 RECORDS
======================================================================

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
0,17:02:00,Monday,18-30,Male,Above high school,Employee,1-2yr,Automobile,Owner,Above 10yr,No defect,Residential areas,NaN,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside-parked vehicles,2,2,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Moving Backward,Slight Injury
1,17:02:00,Monday,31-50,Male,Junior high school,Employee,Above 10yr,Public (> 45 seats),Owner,5-10yrs,No defect,Office areas,Undivided Two way,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury
2,17:02:00,Monday,18-30,Male,Junior high school,Employee,1-2yr,Lorry (41?100Q),Owner,NaN,No defect,Recreational areas,other,NaN,No junction,Asphalt roads,Dry,Daylight,Normal,Collision with roadside objects,2,2,Going straight,Driver or rider,Male,31-50,3,Driver,NaN,Not a Pedestrian,Changing lane to the left,Serious Injury
3,1:06:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Public (> 45 seats),Governmental,NaN,No defect,Office areas,other,Tangent road with mild grade and flat terrain,Y Shape,Earth roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,Pedestrian,Female,18-30,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Slight Injury
4,1:06:00,Sunday,18-30,Male,Junior high school,Employee,2-5yr,NaN,Owner,5-10yrs,No defect,Industrial areas,other,Tangent road with flat terrain,Y Shape,Asphalt roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,2,Going straight,na,na,na,na,NaN,NaN,Not a Pedestrian,Overtaking,Slight Injury

======================================================================
LAST 5 RECORDS
======================================================================

,Time,Day_of_week,Age_band_of_driver,Sex_of_driver,Educational_level,Vehicle_driver_relation,Driving_experience,Type_of_vehicle,Owner_of_vehicle,Service_year_of_vehicle,Defect_of_vehicle,Area_accident_occured,Lanes_or_Medians,Road_allignment,Types_of_Junction,Road_surface_type,Road_surface_conditions,Light_conditions,Weather_conditions,Type_of_collision,Number_of_vehicles_involved,Number_of_casualties,Vehicle_movement,Casualty_class,Sex_of_casualty,Age_band_of_casualty,Casualty_severity,Work_of_casuality,Fitness_of_casuality,Pedestrian_movement,Cause_of_accident,Accident_severity
12311,16:15:00,Wednesday,31-50,Male,NaN,Employee,2-5yr,Lorry (11?40Q),Owner,NaN,No defect,Outside rural areas,Undivided Two way,Tangent road with flat terrain,No junction,Asphalt roads,Dry,Daylight,Normal,Vehicle with vehicle collision,2,1,Going straight,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12312,18:00:00,Sunday,Unknown,Male,Elementary school,Employee,5-10yr,Automobile,Owner,NaN,No defect,Outside rural areas,Two-way (divided with broken lines road marking),Escarpments,No junction,Asphalt roads,Dry,Daylight,Normal,Vehicle with vehicle collision,2,1,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,No distancing,Slight Injury
12313,13:55:00,Sunday,Over 51,Male,Junior high school,Employee,5-10yr,Bajaj,Owner,2-5yrs,No defect,Outside rural areas,Two-way (divided with broken lines road marking),Tangent road with mountainous terrain and,No junction,Asphalt roads,Dry,Daylight,Normal,Vehicle with vehicle collision,1,1,Other,Driver or rider,Male,31-50,3,Driver,Normal,Not a Pedestrian,Changing lane to the right,Serious Injury
12314,13:55:00,Sunday,18-30,Female,Junior high school,Employee,Above 10yr,Lorry (41?100Q),Owner,2-5yrs,No defect,Office areas,Undivided Two way,Tangent road with mountainous terrain and,No junction,Asphalt roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,1,Other,na,na,na,na,Driver,Normal,Not a Pedestrian,Driving under the influence of drugs,Slight Injury
12315,13:55:00,Sunday,18-30,Male,Junior high school,Employee,5-10yr,Other,Owner,2-5yrs,No defect,Outside rural areas,Undivided Two way,Tangent road with mountainous terrain and,O Shape,Asphalt roads,Dry,Darkness - lights lit,Normal,Vehicle with vehicle collision,2,1,Stopping,Pedestrian,Female,5,3,Driver,Normal,Crossing from nearside - masked by parked or s...,Changing lane to the right,Slight Injury

======================================================================
DATASET DIMENSIONS
======================================================================
Rows    : 12,316
Columns : 32

======================================================================
COLUMN NAMES
======================================================================
 1. Time
 2. Day_of_week
 3. Age_band_of_driver
 4. Sex_of_driver
 5. Educational_level
 6. Vehicle_driver_relation
 7. Driving_experience
 8. Type_of_vehicle
 9. Owner_of_vehicle
10. Service_year_of_vehicle
11. Defect_of_vehicle
12. Area_accident_occured
13. Lanes_or_Medians
14. Road_allignment
15. Types_of_Junction
16. Road_surface_type
17. Road_surface_conditions
18. Light_conditions
19. Weather_conditions
20. Type_of_collision
21. Number_of_vehicles_involved
22. Number_of_casualties
23. Vehicle_movement
24. Casualty_class
25. Sex_of_casualty
26. Age_band_of_casualty
27. Casualty_severity
28. Work_of_casuality
29. Fitness_of_casuality
30. Pedestrian_movement
31. Cause_of_accident
32. Accident_severity

======================================================================
DATA TYPES
======================================================================

                         Column Data_Type
0                          Time    object
1                   Day_of_week    object
2            Age_band_of_driver    object
3                 Sex_of_driver    object
4             Educational_level    object
5       Vehicle_driver_relation    object
6            Driving_experience    object
7               Type_of_vehicle    object
8              Owner_of_vehicle    object
9       Service_year_of_vehicle    object
10            Defect_of_vehicle    object
11        Area_accident_occured    object
12             Lanes_or_Medians    object
13              Road_allignment    object
14            Types_of_Junction    object
15            Road_surface_type    object
16      Road_surface_conditions    object
17             Light_conditions    object
18           Weather_conditions    object
19            Type_of_collision    object
20  Number_of_vehicles_involved     int64
21         Number_of_casualties     int64
22             Vehicle_movement    object
23               Casualty_class    object
24              Sex_of_casualty    object
25         Age_band_of_casualty    object
26            Casualty_severity    object
27            Work_of_casuality    object
28         Fitness_of_casuality    object
29          Pedestrian_movement    object
30            Cause_of_accident    object
31            Accident_severity    object

======================================================================
DATASET INFORMATION
======================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12316 entries, 0 to 12315
Data columns (total 32 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Time                         12316 non-null  object
 1   Day_of_week                  12316 non-null  object
 2   Age_band_of_driver           12316 non-null  object
 3   Sex_of_driver                12316 non-null  object
 4   Educational_level            11575 non-null  object
 5   Vehicle_driver_relation      11737 non-null  object
 6   Driving_experience           11487 non-null  object
 7   Type_of_vehicle              11366 non-null  object
 8   Owner_of_vehicle             11834 non-null  object
 9   Service_year_of_vehicle      8388 non-null   object
 10  Defect_of_vehicle            7889 non-null   object
 11  Area_accident_occured        12077 non-null  object
 12  Lanes_or_Medians             11931 non-null  object
 13  Road_allignment              12174 non-null  object
 14  Types_of_Junction            11429 non-null  object
 15  Road_surface_type            12144 non-null  object
 16  Road_surface_conditions      12316 non-null  object
 17  Light_conditions             12316 non-null  object
 18  Weather_conditions           12316 non-null  object
 19  Type_of_collision            12161 non-null  object
 20  Number_of_vehicles_involved  12316 non-null  int64
 21  Number_of_casualties         12316 non-null  int64
 22  Vehicle_movement             12008 non-null  object
 23  Casualty_class               12316 non-null  object
 24  Sex_of_casualty              12316 non-null  object
 25  Age_band_of_casualty         12316 non-null  object
 26  Casualty_severity            12316 non-null  object
 27  Work_of_casuality            9118 non-null   object
 28  Fitness_of_casuality         9681 non-null   object
 29  Pedestrian_movement          12316 non-null  object
 30  Cause_of_accident            12316 non-null  object
 31  Accident_severity            12316 non-null  object
dtypes: int64(2), object(30)
memory usage: 3.0+ MB

======================================================================
NUMERICAL COLUMNS
======================================================================
Number of numerical columns: 2
- Number_of_vehicles_involved
- Number_of_casualties

======================================================================
CATEGORICAL / OBJECT COLUMNS
======================================================================
Number of categorical columns: 30
- Time
- Day_of_week
- Age_band_of_driver
- Sex_of_driver
- Educational_level
- Vehicle_driver_relation
- Driving_experience
- Type_of_vehicle
- Owner_of_vehicle
- Service_year_of_vehicle
- Defect_of_vehicle
- Area_accident_occured
- Lanes_or_Medians
- Road_allignment
- Types_of_Junction
- Road_surface_type
- Road_surface_conditions
- Light_conditions
- Weather_conditions
- Type_of_collision
- Vehicle_movement
- Casualty_class
- Sex_of_casualty
- Age_band_of_casualty
- Casualty_severity
- Work_of_casuality
- Fitness_of_casuality
- Pedestrian_movement
- Cause_of_accident
- Accident_severity

======================================================================
STATISTICAL SUMMARY - NUMERICAL VARIABLES
======================================================================

,count,mean,std,min,25%,50%,75%,max
Number_of_vehicles_involved,12316.000,2.041,0.689,1.000,2.000,2.000,2.000,7.000
Number_of_casualties,12316.000,1.548,1.007,1.000,1.000,1.000,2.000,8.000

======================================================================
STATISTICAL SUMMARY - CATEGORICAL VARIABLES
======================================================================

,count,unique,top,freq
Time,12316,1074,15:30:00,120
Day_of_week,12316,7,Friday,2041
Age_band_of_driver,12316,5,18-30,4271
Sex_of_driver,12316,3,Male,11437
Educational_level,11575,7,Junior high school,7619
Vehicle_driver_relation,11737,4,Employee,9627
Driving_experience,11487,7,5-10yr,3363
Type_of_vehicle,11366,17,Automobile,3205
Owner_of_vehicle,11834,4,Owner,10459
Service_year_of_vehicle,8388,6,Unknown,2883
Defect_of_vehicle,7889,3,No defect,7777
Area_accident_occured,12077,14,Other,3819
Lanes_or_Medians,11931,7,Two-way (divided with broken lines road marking),4411
Road_allignment,12174,9,Tangent road with flat terrain,10459
Types_of_Junction,11429,8,Y Shape,4543
Road_surface_type,12144,5,Asphalt roads,11296
Road_surface_conditions,12316,4,Dry,9340
Light_conditions,12316,4,Daylight,8798
Weather_conditions,12316,9,Normal,10063
Type_of_collision,12161,10,Vehicle with vehicle collision,8774
Vehicle_movement,12008,13,Going straight,8158
Casualty_class,12316,4,Driver or rider,4944
Sex_of_casualty,12316,3,Male,5253
Age_band_of_casualty,12316,6,na,4443
Casualty_severity,12316,4,3,7076
Work_of_casuality,9118,7,Driver,5903
Fitness_of_casuality,9681,5,Normal,9608
Pedestrian_movement,12316,9,Not a Pedestrian,11390
Cause_of_accident,12316,20,No distancing,2263
Accident_severity,12316,3,Slight Injury,10415

======================================================================
NUMBER OF UNIQUE VALUES PER COLUMN
======================================================================

                         Column  Unique_Values  Missing_Values
0                          Time           1074               0
1             Cause_of_accident             20               0
2               Type_of_vehicle             18             950
3         Area_accident_occured             15             239
4              Vehicle_movement             14             308
5             Type_of_collision             11             155
6               Road_allignment             10             142
7             Types_of_Junction              9             887
8            Weather_conditions              9               0
9           Pedestrian_movement              9               0
10            Work_of_casuality              8            3198
11         Number_of_casualties              8               0
12            Educational_level              8             741
13             Lanes_or_Medians              8             385
14           Driving_experience              8             829
15      Service_year_of_vehicle              7            3928
16                  Day_of_week              7               0
17         Age_band_of_casualty              6               0
18         Fitness_of_casuality              6            2635
19  Number_of_vehicles_involved              6               0
20            Road_surface_type              6             172
21           Age_band_of_driver              5               0
22      Vehicle_driver_relation              5             579
23             Owner_of_vehicle              5             482
24               Casualty_class              4               0
25            Defect_of_vehicle              4            4427
26             Light_conditions              4               0
27      Road_surface_conditions              4               0
28            Casualty_severity              4               0
29                Sex_of_driver              3               0
30              Sex_of_casualty              3               0
31            Accident_severity              3               0

======================================================================
SAMPLE UNIQUE VALUES FOR EACH COLUMN
======================================================================

Time
----
['17:02:00' '1:06:00' '14:15:00' '17:30:00' '17:20:00' '14:40:00'
 '17:45:00' '22:45:00' '8:20:00' '15:10:00' '12:11:00' '18:36:00'
 '14:35:00' '12:25:00' '15:30:00']
... and 1059 more unique values

Day_of_week
-----------
['Monday' 'Sunday' 'Friday' 'Wednesday' 'Saturday' 'Thursday' 'Tuesday']

Age_band_of_driver
------------------
['18-30' '31-50' 'Under 18' 'Over 51' 'Unknown']

Sex_of_driver
-------------
['Male' 'Female' 'Unknown']

Educational_level
-----------------
['Above high school' 'Junior high school' 'Elementary school'
 'High school' 'Unknown' 'Illiterate' 'Writing & reading']

Vehicle_driver_relation
-----------------------
['Employee' 'Unknown' 'Owner' 'Other']

Driving_experience
------------------
['1-2yr' 'Above 10yr' '5-10yr' '2-5yr' 'No Licence' 'Below 1yr' 'unknown']

Type_of_vehicle
---------------
['Automobile' 'Public (> 45 seats)' 'Lorry (41?100Q)'
 'Public (13?45 seats)' 'Lorry (11?40Q)' 'Long lorry' 'Public (12 seats)'
 'Taxi' 'Pick up upto 10Q' 'Stationwagen' 'Ridden horse' 'Other' 'Bajaj'
 'Turbo' 'Motorcycle']
... and 2 more unique values

Owner_of_vehicle
----------------
['Owner' 'Governmental' 'Organization' 'Other']

Service_year_of_vehicle
-----------------------
['Above 10yr' '5-10yrs' '1-2yr' '2-5yrs' 'Unknown' 'Below 1yr']

Defect_of_vehicle
-----------------
['No defect' '7' '5']

Area_accident_occured
---------------------
['Residential areas' 'Office areas' '  Recreational areas'
 ' Industrial areas' 'Other' ' Church areas' '  Market areas' 'Unknown'
 'Rural village areas' ' Outside rural areas' ' Hospital areas'
 'School areas' 'Rural village areasOffice areas' 'Recreational areas']

Lanes_or_Medians
----------------
['Undivided Two way' 'other' 'Double carriageway (median)' 'One way'
 'Two-way (divided with solid lines road marking)'
 'Two-way (divided with broken lines road marking)' 'Unknown']

Road_allignment
---------------
['Tangent road with flat terrain'
 'Tangent road with mild grade and flat terrain' 'Escarpments'
 'Tangent road with rolling terrain' 'Gentle horizontal curve'
 'Tangent road with mountainous terrain and'
 'Steep grade downward with mountainous terrain' 'Sharp reverse curve'
 'Steep grade upward with mountainous terrain']

Types_of_Junction
-----------------
['No junction' 'Y Shape' 'Crossing' 'O Shape' 'Other' 'Unknown' 'T Shape'
 'X Shape']

Road_surface_type
-----------------
['Asphalt roads' 'Earth roads' 'Asphalt roads with some distress'
 'Gravel roads' 'Other']

Road_surface_conditions
-----------------------
['Dry' 'Wet or damp' 'Snow' 'Flood over 3cm. deep']

Light_conditions
----------------
['Daylight' 'Darkness - lights lit' 'Darkness - no lighting'
 'Darkness - lights unlit']

Weather_conditions
------------------
['Normal' 'Raining' 'Raining and Windy' 'Cloudy' 'Other' 'Windy' 'Snow'
 'Unknown' 'Fog or mist']

Type_of_collision
-----------------
['Collision with roadside-parked vehicles'
 'Vehicle with vehicle collision' 'Collision with roadside objects'
 'Collision with animals' 'Other' 'Rollover' 'Fall from vehicles'
 'Collision with pedestrians' 'With Train' 'Unknown']

Number_of_vehicles_involved
---------------------------
[2 1 3 6 4 7]

Number_of_casualties
--------------------
[2 1 3 4 6 5 8 7]

Vehicle_movement
----------------
['Going straight' 'U-Turn' 'Moving Backward' 'Turnover' 'Waiting to go'
 'Getting off' 'Reversing' 'Unknown' 'Parked' 'Stopping' 'Overtaking'
 'Other' 'Entering a junction']

Casualty_class
--------------
['na' 'Driver or rider' 'Pedestrian' 'Passenger']

Sex_of_casualty
---------------
['na' 'Male' 'Female']

Age_band_of_casualty
--------------------
['na' '31-50' '18-30' 'Under 18' 'Over 51' '5']

Casualty_severity
-----------------
['na' '3' '2' '1']

Work_of_casuality
-----------------
['Driver' 'Other' 'Unemployed' 'Employee' 'Self-employed' 'Student'
 'Unknown']

Fitness_of_casuality
--------------------
['Normal' 'Deaf' 'Other' 'Blind' 'NormalNormal']

Pedestrian_movement
-------------------
['Not a Pedestrian' "Crossing from driver's nearside"
 'Crossing from nearside - masked by parked or statioNot a Pedestrianry vehicle'
 'Unknown or other'
 'Crossing from offside - masked by  parked or statioNot a Pedestrianry vehicle'
 'In carriageway, statioNot a Pedestrianry - not crossing  (standing or playing)'
 'Walking along in carriageway, back to traffic'
 'Walking along in carriageway, facing traffic'
 'In carriageway, statioNot a Pedestrianry - not crossing  (standing or playing) - masked by parked or statioNot a Pedestrianry vehicle']

Cause_of_accident
-----------------
['Moving Backward' 'Overtaking' 'Changing lane to the left'
 'Changing lane to the right' 'Overloading' 'Other'
 'No priority to vehicle' 'No priority to pedestrian' 'No distancing'
 'Getting off the vehicle improperly' 'Improper parking' 'Overspeed'
 'Driving carelessly' 'Driving at high speed' 'Driving to the left']
... and 5 more unique values

Accident_severity
-----------------
['Slight Injury' 'Serious Injury' 'Fatal injury']

======================================================================
MISSING VALUE OVERVIEW
======================================================================

                         Column  Missing_Count  Missing_Percentage
0             Defect_of_vehicle           4427              35.945
1       Service_year_of_vehicle           3928              31.893
2             Work_of_casuality           3198              25.966
3          Fitness_of_casuality           2635              21.395
4               Type_of_vehicle            950               7.714
5             Types_of_Junction            887               7.202
6            Driving_experience            829               6.731
7             Educational_level            741               6.017
8       Vehicle_driver_relation            579               4.701
9              Owner_of_vehicle            482               3.914
10             Lanes_or_Medians            385               3.126
11             Vehicle_movement            308               2.501
12        Area_accident_occured            239               1.941
13            Road_surface_type            172               1.397
14            Type_of_collision            155               1.259
15              Road_allignment            142               1.153
16                Sex_of_driver              0               0.000
17           Age_band_of_driver              0               0.000
18                  Day_of_week              0               0.000
19                         Time              0               0.000
20           Weather_conditions              0               0.000
21  Number_of_vehicles_involved              0               0.000
22             Light_conditions              0               0.000
23      Road_surface_conditions              0               0.000
24               Casualty_class              0               0.000
25         Number_of_casualties              0               0.000
26         Age_band_of_casualty              0               0.000
27              Sex_of_casualty              0               0.000
28            Casualty_severity              0               0.000
29          Pedestrian_movement              0               0.000
30            Cause_of_accident              0               0.000
31            Accident_severity              0               0.000

======================================================================
DUPLICATE RECORD CHECK
======================================================================
Number of duplicate rows: 0
No exact duplicate records detected.

======================================================================
ACCIDENT SEVERITY - INITIAL DISTRIBUTION
======================================================================

                   Count  Percentage
Accident_severity
Slight Injury      10415      84.565
Serious Injury      1743      14.152
Fatal injury         158       1.283

======================================================================
NUMBER OF CASUALTIES - INITIAL SUMMARY
======================================================================

count   12316.000
mean        1.548
std         1.007
min         1.000
25%         1.000
50%         1.000
75%         2.000
max         8.000
Name: Number_of_casualties, dtype: float64

Total casualties recorded: 19,067

======================================================================
TIME COLUMN - INITIAL INSPECTION
======================================================================
Data type of Time column: object

Sample time values:

0    17:02:00
1    17:02:00
2    17:02:00
3     1:06:00
4     1:06:00
5    14:15:00
6    17:30:00
7    17:20:00
8    17:20:00
9    17:20:00
Name: Time, dtype: object

Number of unique time values:
1074

======================================================================
DATASET MEMORY USAGE
======================================================================
Memory used by dataset: 20.82 MB

======================================================================
STEP 2 COMPLETED
======================================================================
Dataset shape : (12316, 32)
Rows          : 12,316
Columns       : 32
Duplicates    : 0
Memory usage  : 20.82 MB

The dataset is now loaded and initially understood.
Detailed cleaning and treatment will be performed in Step 3.

In [ ]:
# ============================================================
# STEP 3: DATA CLEANING
# RTA / ACCIDENT DATASET ANALYSIS
# ============================================================


# ============================================================
# 3.1 CREATE A WORKING COPY
# ============================================================

# Keep df_original untouched.
# All cleaning operations will be performed on df.

df = df_original.copy()

print("=" * 70)
print("DATA CLEANING STARTED")
print("=" * 70)


# ============================================================
# 3.2 CHECK DATASET SHAPE BEFORE CLEANING
# ============================================================

print("\n" + "=" * 70)
print("DATASET SHAPE BEFORE CLEANING")
print("=" * 70)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]}")

======================================================================
DATA CLEANING STARTED
======================================================================

======================================================================
DATASET SHAPE BEFORE CLEANING
======================================================================
Rows    : 12,316
Columns : 32

In [ ]:
# ============================================================
# 3.3 STANDARDIZE COLUMN NAMES
# ============================================================

# Remove accidental spaces from column names
# and replace spaces with underscores.

df.columns = (
    df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print("\n" + "=" * 70)
print("COLUMN NAMES AFTER STANDARDIZATION")
print("=" * 70)

print(df.columns.tolist())

======================================================================
COLUMN NAMES AFTER STANDARDIZATION
======================================================================
['Time', 'Day_of_week', 'Age_band_of_driver', 'Sex_of_driver', 'Educational_level', 'Vehicle_driver_relation', 'Driving_experience', 'Type_of_vehicle', 'Owner_of_vehicle', 'Service_year_of_vehicle', 'Defect_of_vehicle', 'Area_accident_occured', 'Lanes_or_Medians', 'Road_allignment', 'Types_of_Junction', 'Road_surface_type', 'Road_surface_conditions', 'Light_conditions', 'Weather_conditions', 'Type_of_collision', 'Number_of_vehicles_involved', 'Number_of_casualties', 'Vehicle_movement', 'Casualty_class', 'Sex_of_casualty', 'Age_band_of_casualty', 'Casualty_severity', 'Work_of_casuality', 'Fitness_of_casuality', 'Pedestrian_movement', 'Cause_of_accident', 'Accident_severity']

In [ ]:
# ============================================================
# 3.4 CHECK MISSING VALUES
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUES BEFORE TREATMENT")
print("=" * 70)

missing_before = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().mean().values * 100
    )
})

missing_before = missing_before[
    missing_before["Missing_Count"] > 0
].sort_values(
    by="Missing_Count",
    ascending=False
)

display(missing_before)

======================================================================
MISSING VALUES BEFORE TREATMENT
======================================================================

                     Column  Missing_Count  Missing_Percentage
10        Defect_of_vehicle           4427              35.945
9   Service_year_of_vehicle           3928              31.893
27        Work_of_casuality           3198              25.966
28     Fitness_of_casuality           2635              21.395
7           Type_of_vehicle            950               7.714
14        Types_of_Junction            887               7.202
6        Driving_experience            829               6.731
4         Educational_level            741               6.017
5   Vehicle_driver_relation            579               4.701
8          Owner_of_vehicle            482               3.914
12         Lanes_or_Medians            385               3.126
22         Vehicle_movement            308               2.501
11    Area_accident_occured            239               1.941
15        Road_surface_type            172               1.397
19        Type_of_collision            155               1.259
13          Road_allignment            142               1.153

In [ ]:
# ============================================================
# 3.5 IDENTIFY LITERAL 'NA' VALUES
# ============================================================

print("\n" + "=" * 70)
print("LITERAL 'NA' VALUES")
print("=" * 70)

literal_na_before = (
    df.astype(str)
    .apply(
        lambda column: column.str.strip().str.lower().eq("na")
    )
    .sum()
)

literal_na_before = (
    literal_na_before[
        literal_na_before > 0
    ]
    .sort_values(ascending=False)
    .to_frame("Literal_NA_Count")
)

display(literal_na_before)

======================================================================
LITERAL 'NA' VALUES
======================================================================

                      Literal_NA_Count
Casualty_class                    4443
Sex_of_casualty                   4443
Age_band_of_casualty              4443
Casualty_severity                 4443

In [ ]:
# ============================================================
# 3.6 STANDARDIZE MISSING VALUE REPRESENTATIONS
# ============================================================

# Convert common representations of missing data into NaN.

missing_values = [
    "na",
    "NA",
    "N/A",
    "n/a",
    "null",
    "NULL",
    "None",
    "none",
    ""
]

df = df.replace(
    missing_values,
    np.nan
)

In [ ]:
# ============================================================
# 3.7 CHECK MISSING VALUES AFTER STANDARDIZATION
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUES AFTER STANDARDIZATION")
print("=" * 70)

missing_after_standardization = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().mean().values * 100
    )
})

missing_after_standardization = (
    missing_after_standardization[
        missing_after_standardization["Missing_Count"] > 0
    ]
    .sort_values(
        by="Missing_Count",
        ascending=False
    )
)

display(missing_after_standardization)

======================================================================
MISSING VALUES AFTER STANDARDIZATION
======================================================================

                     Column  Missing_Count  Missing_Percentage
24          Sex_of_casualty           4443              36.075
23           Casualty_class           4443              36.075
26        Casualty_severity           4443              36.075
25     Age_band_of_casualty           4443              36.075
10        Defect_of_vehicle           4427              35.945
9   Service_year_of_vehicle           3928              31.893
27        Work_of_casuality           3198              25.966
28     Fitness_of_casuality           2635              21.395
7           Type_of_vehicle            950               7.714
14        Types_of_Junction            887               7.202
6        Driving_experience            829               6.731
4         Educational_level            741               6.017
5   Vehicle_driver_relation            579               4.701
8          Owner_of_vehicle            482               3.914
12         Lanes_or_Medians            385               3.126
22         Vehicle_movement            308               2.501
11    Area_accident_occured            239               1.941
15        Road_surface_type            172               1.397
19        Type_of_collision            155               1.259
13          Road_allignment            142               1.153

In [ ]:

# ============================================================
# 3.8 CHECK DUPLICATES
# ============================================================

print("\n" + "=" * 70)
print("DUPLICATE RECORDS")
print("=" * 70)

duplicate_count_before = df.duplicated().sum()

print(
    f"Duplicate rows found: "
    f"{duplicate_count_before:,}"
)

======================================================================
DUPLICATE RECORDS
======================================================================
Duplicate rows found: 0

In [ ]:
# ============================================================
# 3.9 DISPLAY DUPLICATE RECORDS
# ============================================================

if duplicate_count_before > 0:

    print("\nSample duplicate records:")

    display(
        df[df.duplicated(keep=False)]
        .sort_values(by=df.columns.tolist())
        .head(20)
    )

else:

    print("No duplicate records found.")

No duplicate records found.

In [ ]:
# ============================================================
# 3.10 REMOVE EXACT DUPLICATES
# ============================================================

df = df.drop_duplicates().reset_index(drop=True)

print("\nDuplicate records removed.")

Duplicate records removed.

In [ ]:
# ============================================================
# 3.11 CHECK DATA TYPES
# ============================================================

print("\n" + "=" * 70)
print("DATA TYPES BEFORE CONVERSION")
print("=" * 70)

display(
   df.dtypes
)

======================================================================
DATA TYPES BEFORE CONVERSION
======================================================================

Time                           object
Day_of_week                    object
Age_band_of_driver             object
Sex_of_driver                  object
Educational_level              object
Vehicle_driver_relation        object
Driving_experience             object
Type_of_vehicle                object
Owner_of_vehicle               object
Service_year_of_vehicle        object
Defect_of_vehicle              object
Area_accident_occured          object
Lanes_or_Medians               object
Road_allignment                object
Types_of_Junction              object
Road_surface_type              object
Road_surface_conditions        object
Light_conditions               object
Weather_conditions             object
Type_of_collision              object
Number_of_vehicles_involved     int64
Number_of_casualties            int64
Vehicle_movement               object
Casualty_class                 object
Sex_of_casualty                object
Age_band_of_casualty           object
Casualty_severity              object
Work_of_casuality              object
Fitness_of_casuality           object
Pedestrian_movement            object
Cause_of_accident              object
Accident_severity              object
dtype: object

In [ ]:
# ============================================================
# 3.12 CONVERT NUMERICAL COLUMNS
# ============================================================

# These variables represent numerical quantities.
# errors='coerce' converts invalid entries into NaN,
# allowing us to identify them later.

numerical_columns_expected = [
    "Number_of_vehicles_involved",
    "Number_of_casualties"
]

for column in numerical_columns_expected:

    if column in df.columns:

        df[column] = pd.to_numeric(
            df[column],
            errors="coerce"
        )

In [ ]:
# ============================================================
# 3.13 CONVERT TIME COLUMN
# ============================================================

print("\n" + "=" * 70)
print("TIME COLUMN CONVERSION")
print("=" * 70)

if "Time" in df.columns:

    print("Time data type before conversion:")
    print(df["Time"].dtype)

    df["Time"] = pd.to_datetime(
        df["Time"],
        format="%H:%M:%S",
        errors="coerce"
    )

    print("\nTime data type after conversion:")
    print(df["Time"].dtype)

======================================================================
TIME COLUMN CONVERSION
======================================================================
Time data type before conversion:
object

Time data type after conversion:
datetime64[ns]

In [ ]:
# ============================================================
# 3.14 CHECK INVALID TIME VALUES
# ============================================================

if "Time" in df.columns:

    invalid_time_count = df["Time"].isna().sum()

    print(
        f"\nInvalid / missing time values: "
        f"{invalid_time_count:,}"
    )

Invalid / missing time values: 0

In [ ]:
# ============================================================
# 3.15 STANDARDIZE TEXT COLUMNS
# ============================================================

# Remove unnecessary spaces from categorical/text variables.

text_columns = df.select_dtypes(
    include="object"
).columns

for column in text_columns:

    df[column] = (
        df[column]
        .str.strip()
    )

In [ ]:

# ============================================================
# 3.16 CHECK UNIQUE VALUES OF IMPORTANT CATEGORICAL COLUMNS
# ============================================================

important_categorical_columns = [
    "Day_of_week",
    "Age_band_of_driver",
    "Sex_of_driver",
    "Educational_level",
    "Driving_experience",
    "Type_of_vehicle",
    "Vehicle_driver_relation",
    "Area_accident_occured",
    "Lanes_or_Medians",
    "Road_allignment",
    "Types_of_Junction",
    "Road_surface_type",
    "Road_surface_conditions",
    "Light_conditions",
    "Weather_conditions",
    "Vehicle_movement",
    "Accident_severity"
]

print("\n" + "=" * 70)
print("IMPORTANT CATEGORICAL VARIABLES")
print("=" * 70)

for column in important_categorical_columns:

    if column in df.columns:

        print(f"\n{column}")
        print("-" * 50)

        display(
            df[column]
            .value_counts(dropna=False)
            .to_frame("Count")
        )

======================================================================
IMPORTANT CATEGORICAL VARIABLES
======================================================================

Day_of_week
--------------------------------------------------

             Count
Day_of_week
Friday        2041
Thursday      1851
Wednesday     1840
Tuesday       1770
Monday        1681
Saturday      1666
Sunday        1467

Age_band_of_driver
--------------------------------------------------

                    Count
Age_band_of_driver
18-30                4271
31-50                4087
Over 51              1585
Unknown              1548
Under 18              825

Sex_of_driver
--------------------------------------------------

               Count
Sex_of_driver
Male           11437
Female           701
Unknown          178

Educational_level
--------------------------------------------------

                    Count
Educational_level
Junior high school   7619
Elementary school    2163
High school          1110
NaN                   741
Above high school     362
Writing & reading     176
Unknown               100
Illiterate             45

Driving_experience
--------------------------------------------------

                    Count
Driving_experience
5-10yr               3363
2-5yr                2613
Above 10yr           2262
1-2yr                1756
Below 1yr            1342
NaN                   829
No Licence            118
unknown                33

Type_of_vehicle
--------------------------------------------------

                      Count
Type_of_vehicle
Automobile             3205
Lorry (41?100Q)        2186
Other                  1208
NaN                     950
Pick up upto 10Q        811
Public (12 seats)       711
Stationwagen            687
Lorry (11?40Q)          541
Public (13?45 seats)    532
Public (> 45 seats)     404
Long lorry              383
Taxi                    265
Motorcycle              177
Special vehicle          84
Ridden horse             76
Turbo                    46
Bajaj                    29
Bicycle                  21

Vehicle_driver_relation
--------------------------------------------------

                         Count
Vehicle_driver_relation
Employee                  9627
Owner                     1973
NaN                        579
Other                      123
Unknown                     14

Area_accident_occured
--------------------------------------------------

                                 Count
Area_accident_occured
Other                             3819
Office areas                      3451
Residential areas                 2060
Church areas                      1060
Industrial areas                   456
School areas                       415
Recreational areas                 328
NaN                                239
Outside rural areas                218
Hospital areas                     121
Market areas                        63
Rural village areas                 44
Unknown                             22
Rural village areasOffice areas     20

Lanes_or_Medians
--------------------------------------------------

                                                  Count
Lanes_or_Medians
Two-way (divided with broken lines road marking)   4411
Undivided Two way                                  3796
other                                              1660
Double carriageway (median)                        1020
One way                                             845
NaN                                                 385
Two-way (divided with solid lines road marking)     142
Unknown                                              57

Road_allignment
--------------------------------------------------

                                               Count
Road_allignment
Tangent road with flat terrain                 10459
Tangent road with mild grade and flat terrain    501
Steep grade downward with mountainous terrain    429
Tangent road with mountainous terrain and        396
Gentle horizontal curve                          163
NaN                                              142
Escarpments                                      113
Sharp reverse curve                               57
Tangent road with rolling terrain                 37
Steep grade upward with mountainous terrain       19

Types_of_Junction
--------------------------------------------------

                   Count
Types_of_Junction
Y Shape             4543
No junction         3837
Crossing            2177
NaN                  887
Other                445
Unknown              191
O Shape              164
T Shape               60
X Shape               12

Road_surface_type
--------------------------------------------------

                                  Count
Road_surface_type
Asphalt roads                     11296
Earth roads                         358
Gravel roads                        242
NaN                                 172
Other                               167
Asphalt roads with some distress     81

Road_surface_conditions
--------------------------------------------------

                         Count
Road_surface_conditions
Dry                       9340
Wet or damp               2904
Snow                        70
Flood over 3cm. deep         2

Light_conditions
--------------------------------------------------

                         Count
Light_conditions
Daylight                  8798
Darkness - lights lit     3286
Darkness - no lighting     192
Darkness - lights unlit     40

Weather_conditions
--------------------------------------------------

                    Count
Weather_conditions
Normal              10063
Raining              1331
Other                 296
Unknown               292
Cloudy                125
Windy                  98
Snow                   61
Raining and Windy      40
Fog or mist            10

Vehicle_movement
--------------------------------------------------

                     Count
Vehicle_movement
Going straight        8158
Moving Backward        985
Other                  937
Reversing              563
Turnover               489
Getting off            339
NaN                    308
Entering a junction    193
Overtaking              96
Unknown                 88
Stopping                61
U-Turn                  50
Waiting to go           39
Parked                  10

Accident_severity
--------------------------------------------------

                   Count
Accident_severity
Slight Injury      10415
Serious Injury      1743
Fatal injury         158

In [ ]:
# ============================================================
# 3.17 CHECK NUMERICAL VARIABLES FOR INVALID VALUES
# ============================================================

print("\n" + "=" * 70)
print("NUMERICAL VARIABLE VALIDATION")
print("=" * 70)

# Number of vehicles should be positive
if "Number_of_vehicles_involved" in df.columns:

    print("\nNumber of vehicles involved:")

    print(
        "Values <= 0:",
        (df["Number_of_vehicles_involved"] <= 0).sum()
    )


# Number of casualties should be positive
if "Number_of_casualties" in df.columns:

    print("\nNumber of casualties:")

    print(
        "Values <= 0:",
        (df["Number_of_casualties"] <= 0).sum()
    )

======================================================================
NUMERICAL VARIABLE VALIDATION
======================================================================

Number of vehicles involved:
Values <= 0: 0

Number of casualties:
Values <= 0: 0

In [ ]:
# ============================================================
# 3.18 CHECK ACCIDENT SEVERITY VALUES
# ============================================================

print("\n" + "=" * 70)
print("ACCIDENT SEVERITY VALIDATION")
print("=" * 70)

display(
    df["Accident_severity"]
    .value_counts(dropna=False)
)

======================================================================
ACCIDENT SEVERITY VALIDATION
======================================================================

Accident_severity
Slight Injury     10415
Serious Injury     1743
Fatal injury        158
Name: count, dtype: int64

In [ ]:
# ============================================================
# 3.19 MISSING VALUE TREATMENT
# ============================================================

print("\n" + "=" * 70)
print("MISSING VALUE TREATMENT")
print("=" * 70)

# Display missing values before treatment

missing_summary = pd.DataFrame({
    "Column": df.columns,
    "Missing_Count": df.isnull().sum().values,
    "Missing_Percentage": (
        df.isnull().mean().values * 100
    )
})

missing_summary = (
    missing_summary[
        missing_summary["Missing_Count"] > 0
    ]
    .sort_values(
        by="Missing_Count",
        ascending=False
    )
)

display(missing_summary)


# ============================================================
# IMPORTANT:
# DO NOT AUTOMATICALLY DROP OR IMPUTE ALL MISSING VALUES YET.
# ============================================================

print(
    "\nMissing values identified."
)

print(
    "The appropriate treatment will depend on the variable "
    "and its analytical importance."
)

======================================================================
MISSING VALUE TREATMENT
======================================================================

                     Column  Missing_Count  Missing_Percentage
24          Sex_of_casualty           4443              36.075
23           Casualty_class           4443              36.075
26        Casualty_severity           4443              36.075
25     Age_band_of_casualty           4443              36.075
10        Defect_of_vehicle           4427              35.945
9   Service_year_of_vehicle           3928              31.893
27        Work_of_casuality           3198              25.966
28     Fitness_of_casuality           2635              21.395
7           Type_of_vehicle            950               7.714
14        Types_of_Junction            887               7.202
6        Driving_experience            829               6.731
4         Educational_level            741               6.017
5   Vehicle_driver_relation            579               4.701
8          Owner_of_vehicle            482               3.914
12         Lanes_or_Medians            385               3.126
22         Vehicle_movement            308               2.501
11    Area_accident_occured            239               1.941
15        Road_surface_type            172               1.397
19        Type_of_collision            155               1.259
13          Road_allignment            142               1.153

Missing values identified.
The appropriate treatment will depend on the variable and its analytical importance.

In [ ]:

# ============================================================
# 3.20 CREATE CLEANED DATASET STATUS
# ============================================================

print("\n" + "=" * 70)
print("CURRENT CLEANED DATASET STATUS")
print("=" * 70)

print(f"Rows    : {df.shape[0]:,}")
print(f"Columns : {df.shape[1]:,}")

print(
    f"\nRemaining duplicate rows: "
    f"{df.duplicated().sum():,}"
)

======================================================================
CURRENT CLEANED DATASET STATUS
======================================================================
Rows    : 12,316
Columns : 32

Remaining duplicate rows: 0

In [ ]:
# ============================================================
# 3.21 SAVE CLEANED DATASET
# ============================================================

# We will save the current cleaned version.
# Further feature engineering will happen later.

df_cleaned = df.copy()


# ============================================================
# 3.22 FINAL CLEANING SUMMARY
# ============================================================

print("\n" + "=" * 70)
print("STEP 3 - INITIAL DATA CLEANING COMPLETED")
print("=" * 70)

print(
    f"Original rows : {df_original.shape[0]:,}"
)

print(
    f"Current rows  : {df.shape[0]:,}"
)

print(
    f"Rows removed  : "
    f"{df_original.shape[0] - df.shape[0]:,}"
)

print(
    f"Columns       : {df.shape[1]:,}"
)

print("\nData has been standardized and validated.")
print("Remaining missing values will be treated based on column importance.")

======================================================================
STEP 3 - INITIAL DATA CLEANING COMPLETED
======================================================================
Original rows : 12,316
Current rows  : 12,316
Rows removed  : 0
Columns       : 32

Data has been standardized and validated.
Remaining missing values will be treated based on column importance.